# List all available commands
default:
  just --list

# Apply current macOS configuration
darwin-rebuild:
  sudo darwin-rebuild switch --flake ~/config/nix

# First time run of darwin-rebuild
darwin-rebuild-setup:
  sudo nix run nix-darwin/nix-darwin-25.05#darwin-rebuild -- --flake ~/config/nix/flake.nix# switch
