# List all available commands
default:
  just --list

# Apply current macOS configuration
darwin-rebuild:
  sudo darwin-rebuild switch --flake ~/config/nix#simple

# First time run of darwin-rebuild (you need a new shell afterwards for darwin-rebuild to work)
darwin-rebuild-setup:
  sudo nix run nix-darwin/nix-darwin-25.05#darwin-rebuild -- --flake ~/config/nix#simple switch
